version: '3.8'

services:
  backend:
    build:
      context: ./CSpider-be
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ./articles.db:/app/articles.db
    networks:
      - app-network

  frontend:
    build:
      context: ./CSpider-fe
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
